name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: Build the Docker image
      run: docker build . --file Dockerfile --tag paulridgway/ovpn-browser:$(date +%s)
  
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: jerray/publish-docker-action@master
      name: Publish
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        registry: docker.pkg.github.com
        repository: paulridgway/ovpn-browser~