name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - id: checkout
      uses: actions/checkout@v2
    - id: docker-build
      name: Build the Docker image
      run: docker build . --file Dockerfile --tag paulridgway/ovpn-browser:$(date +%s)
  
  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - id: docker-publish
      uses: jerray/publish-docker-action@master
      name: Publish
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        registry: hub.docker.com
        repository: paulridgway/ovpn-browser~